Post/urls.py
from django.urls import path, include
from Post.Api.api import PostAPIView, PostRudView, CommentAPIView, CommentRudView, ReactionAPIView, ReactionRudView, PictureAPIView, PictureRudView
from . import views

api_urlpatterns = [
    path('post/', PostAPIView.as_view(), name='post-listCreate'),
    path('post/<pk>', PostRudView.as_view(), name='post-rud'),
    path('post/<pk>/comment', views.post_comments, name='post_comments'),
    path('post/<pk>/picture', views.post_picture, name='post_picture'),


    path('comment/', CommentAPIView.as_view(), name='comment-listCreate'),
    path('comment/<pk>', CommentRudView.as_view(), name='comment-rud'),

    path('reaction/', ReactionAPIView.as_view(), name='reaction-listCreate'),
    path('reaction/<pk>', ReactionRudView.as_view(), name='reaction-rud'),
    path('reaction/user/<pk>', views.user_reactions, name='user_reactions'),

    path('picture/', PictureAPIView.as_view(), name='pictureCreate'),
    path('picture/<pk>', PictureRudView.as_view(), name='picture-rud'),

]

urlpatterns = [
    path('', include(api_urlpatterns)),     # api url patterns
]

SbaClean/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from rest_framework.authtoken.views import obtain_auth_token
from django.conf import settings
from django.conf.urls.static import static
from rest_framework_swagger.views import get_swagger_view
from django.contrib.auth import views as auth_views
from webapp.views import UploadView
from webapp import views
from django.conf.urls import handler404, handler500

schema_view = get_swagger_view(title='SbaClean API')
api_urlpatterns = [
    path('', schema_view),
    path('accounts/', include(('Accounts.urls', 'Accounts'), namespace='api-accounts')),
    path('address/', include(('Address.urls', 'Address'), namespace='api-address')),
    path('posts/', include(('Post.urls', 'Post'), namespace='api-posts')),
    path('anomalys/', include(('Anomaly.urls', 'Anomaly'), namespace='api-anomaly')),
    path('events/', include(('Event.urls', 'Event'), namespace='api-event')),
    path('mobile/', include('mobile.urls')),
    path('notification/', include('notification.urls')),

]

urlpatterns = [
                  path('', views.index),
                  path('login/', views.login, name='login'),
                  path('accounts/login/', views.login, name='login'),
                  path('register/', views.register, name='register'),
                  path('feed/', views.feed, name='feed'),
                  path('event/', views.event, name='event'),
                  path('profile/', views.profile, name='profile'),
                  path('post_details/', views.feed, name='post_details'),
                  path('social-auth/', views.social_auth, name='social_auth'),
                  path('', include('social_django.urls', namespace='social')),
                  path("logout/", views.logout, name="logout"),
                  path('', include('dashboard.urls', namespace='dashboard')),
                  path('api/upload-image', UploadView.as_view()),


    path('admin/', admin.site.urls),
    path('api-token-auth/', obtain_auth_token, name='api_token_auth'),
    path('api/v1/', include(api_urlpatterns)),
    url(r'^rest-auth/', include('rest_auth.urls')),
    url(r'^like/$',views.like_post,name="like_post"),
    url(r'^dislike/$',views.dislike_post,name="dislike_post"),
    url(r'^signaled/$',views.signaled,name="signaled"),
    url(r'^post_delete/$',views.post_delete,name="post_delete"),
    url(r'^post_edit/$',views.post_edit,name="post_edit"),
    url(r'^Myposts/$',views.Myposts,name="Myposts"),
    url(r'^Myreactions/$',views.Myreactions,name="Myreactions"),
    url(r'^comment_delete/$',views.comment_delete,name="comment_delete"),
    url(r'^create_comment/$',views.create_comment,name="create_comment"),
    url(r'^Participate/$',views.Participate,name="Participate")


              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



handler404 = views.error_404
handler500 = views.error_500

dashboard/urls.py
from django.urls import path, include
from dashboard import views as dash_views


app_name = "dashboard"

urlpatterns = [
    path('dashboard/', dash_views.dashboard_index, name="dashboard"),
    path('dashboard/anomalies', dash_views.dashboard_anomalies, name="dashboard_anomalies"),
    path('dashboard/anomalies/edit/<int:pid>', dash_views.dashboard_anomalie_edit, name="dashboard_anomalie_edit"),
    path('dashboard/anomalies/archive/<int:pid>', dash_views.dashboard_anomalie_archive, name="dashboard_anomalie_archive"),
    path('dashboard/archives', dash_views.dashboard_archives, name="dashboard_archives"),
    path('dashboard/users', dash_views.dashboard_users, name="dashboard_users"),
    path('dashboard/users/edit/<int:pid>', dash_views.dashboard_users_edit, name="dashboard_users_edit"),
    path('dashboard/comments', dash_views.dashboard_comments, name="dashboard_comments"),
    path('dashboard/comments/edit/<int:pid>', dash_views.dashboard_comments_edit, name="dashboard_comments_edit"),
    path('dashboard/reports', dash_views.dashboard_reports, name="dashboard_reports"),
    path('dashboard/reports/edit/<int:pid>', dash_views.dashboard_reports_edit, name="dashboard_reports_edit"),
    path('dashboard/events', dash_views.dashboard_events, name="dashboard_events"),
    path('dashboard/event/approve/<int:eid>', dash_views.dashboard_event_approve, name="dashboard_event_approve"),
    path('dashboard/events/edit/<int:pid>', dash_views.dashboard_events_edit, name="dashboard_events_edit"),            
]

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/views.py
from django.contrib.auth import authenticate
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from django.utils.translation import gettext as _
from django.db import transaction
from .models import *
from .form import *
from Post.models import *
from Anomaly.models import *
from Address.models import *
from Accounts.models import *
from Event.models import *
from django.contrib.admin.views.decorators import staff_member_required
from datetime import datetime
import json 

menu = [
    {
    "title": "Dashboard",
    "status": "active",
    "url": "dashboard:dashboard",
    "icon": "dashboard"
    },
    {
    "title": "Anomalies",
    "status": "",
    "url": "dashboard:dashboard_anomalies",
    "icon": "report_problem"
    },
    {
    "title": "Anomalies archivées",
    "status": "",
    "url": "dashboard:dashboard_archives",
    "icon": "check_circle_outline"
    },    
    {
    "title": "Evénements",
    "status": "",
    "url": "dashboard:dashboard_events",
    "icon": "calendar_today"
    },
    {
    "title": "Utilisateurs",
    "status": "",
    "url": "dashboard:dashboard_users",
    "icon": "person"
    },
    # {
    # "title": "Commentaires",
    # "status": "",
    # "url": "dashboard:dashboard_comments",
    # "icon": "comment"
    # },
    {
    "title": "Signalements",
    "status": "",
    "url": "dashboard:dashboard_reports",
    "icon": "info"
    }
]

def notifications(request):
    # Getting actual number of Users, Anomalies, Events and archives
    users_count = MyUser.objects.all().count()
    anomalies_count = Anomaly.objects.filter().count()
    events_count = Event.objects.all().count()
    archives_count = Anomaly.objects.filter(archived=True).count()

    # Getting the session stored numbers
    if not request.session.get('users_count'):
        request.session['users_count'] = users_count
    my_users_count = request.session['users_count']
    request.session['users_count'] = users_count

    if not request.session.get('anomalies_count'):
        request.session['anomalies_count'] = anomalies_count    
    my_anomalies_count = request.session['anomalies_count']
    request.session['anomalies_count'] = anomalies_count    

    if not request.session.get('events_count'):
        request.session['events_count'] = events_count        
    my_events_count = request.session['events_count']
    request.session['events_count'] = events_count        

    if not request.session.get('archives_count'):
        request.session['archives_count'] = archives_count    
    my_archives_count = request.session['archives_count']
    request.session['archives_count'] = archives_count    

    notifications = {
        "users_count": users_count - my_users_count,
        "anomalies_count": anomalies_count - my_anomalies_count,
        "events_count": events_count - my_events_count,
        "archives_count": archives_count - my_archives_count
    }
    return notifications

def menu_active(title):
    for item in menu:
        if item["title"] == title:
            item["status"] = "active"
        else:
            item["status"] = ""

@staff_member_required
def dashboard_index(request):
    menu_active('Dashboard')
    notif = notifications(request)
    users_count = MyUser.objects.all().count()
    anomalies_count = Anomaly.objects.filter(archived=False).count()
    events_count = Event.objects.all().count()
    archives_count = Anomaly.objects.filter(archived=True).count()
    anomalies = Anomaly.objects.all()
    monthly = []
    now_month = datetime.now().month
    now_year = datetime.now().year
    for i in range(1,32):
        monthly.append(0)
    for a in anomalies:
        for i in range(1,32):
            if (a.post.created_at.day == i) and (a.post.created_at.month == now_month) and (a.post.created_at.year == now_year):
                monthly[i-1]+=1;
    stats = {
        "users": users_count,
        "anomalies": anomalies_count,
        "events": events_count,
        "archives": archives_count,
        "monthly": monthly
    }
    context = {"menu": menu, "stats": stats, "anomalies": anomalies, "notifications": notif}
    return render(request, 'index_dashboard.html', context)

@staff_member_required
def dashboard_anomalies(request):
    menu_active('Anomalies')
    if request.method == 'POST':
        action = request.POST.get('action')
        if action == 'delete':
            post_id = request.POST.get('post_id')
            posts = Post.objects.filter(id=post_id).delete()
    anomalies = Anomaly.objects.filter(archived=False)
    context = {"menu": menu, "anomalies": anomalies }
    return render(request, 'anomalies.html', context)

@staff_member_required
def dashboard_anomalie_edit(request, pid):
    menu_active('Anomalies')
    post = Post.objects.get(id=pid)
    form = PostForm(request.POST or None, instance = post)
    if request.method == 'POST':
        action = request.POST.get('action')
        if action == 'edit' and form.is_valid():
            form.save()
            return redirect('dashboard:dashboard_anomalies')

    context = {'menu': menu, 'post': post, 'form': form}
    return render(request, 'anomalie_edit.html', context)

@staff_member_required
def dashboard_anomalie_archive(request, pid):
    menu_active('Anomalies')
    anomaly = Anomaly.objects.get(post=pid)
    anomaly.archive()
    return redirect('dashboard:dashboard_anomalies')

@staff_member_required
def dashboard_archives(request):
    menu_active('Anomalies archivées')
    if request.method == 'POST':
        action = request.POST.get('action')
        if action == 'delete':
            post_id = request.POST.get('post_id')
            posts = Post.objects.filter(id=post_id).delete()
    anomalies = Anomaly.objects.filter(archived=True)
    context = {"menu": menu, "anomalies": anomalies }
    return render(request, 'archives.html', context)

@staff_member_required
def dashboard_users(request):
    menu_active('Utilisateurs')
    if request.method == 'POST' and request.POST.get('action') == 'ban':
        user_id = request.POST.get('user_id')
        users = MyUser.objects.filter(id=user_id)[0].ban()
    users = MyUser.objects.all()
    context = {'menu': menu, 'users': users}
    return render(request, 'users.html', context)

@staff_member_required
def dashboard_users_edit(request):
    menu_active('Utilisateurs')
    context = {'menu': menu}
    return render(request, 'users.html', context)

@staff_member_required
def dashboard_events(request):
    menu_active('Evénements')
    if request.method == 'POST':
        action = request.POST.get('action')
        if action == 'delete':
            post_id = request.POST.get('post_id')
            posts = Post.objects.filter(id=post_id).delete()
    events = Event.objects.all()
    context = {"menu": menu, "events": events }
    return render(request, 'events.html', context)

@staff_member_required
def dashboard_event_approve(request, eid):
    now_time = datetime.now()
    event = Event.objects.filter(id=eid)[0].approve(request.user, now_time)
    return redirect('dashboard:dashboard_events')

@staff_member_required
def dashboard_events_edit(request):
    menu_active('Evénements')
    context = {'menu': menu, }
    return render(request, 'events.html', context)

@staff_member_required
def dashboard_comments(request):
    menu_active('Commentaires') 
    if request.method == 'POST' and request.POST.get('action') == 'delete':
        comment_id = request.POST.get('comment_id')
        Comment.objects.filter(id=user_id).delete()
    comments = Comment.objects.all()
    context = {'menu': menu, 'comments': comments}
    return render(request, 'comments.html', context)

@staff_member_required
def dashboard_comments_edit(request):
    menu_active('Commentaires')    
    context = {'menu': menu, }
    return render(request, 'comments.html', context)

@staff_member_required
def dashboard_reports(request):
    menu_active('Signalements')
    if request.method == 'POST' and request.POST.get('action') == 'ban':
        user_id = request.POST.get('user_id')
        users = MyUser.objects.filter(id=user_id)[0].ban()
    if request.method == 'POST' and request.POST.get('action') == 'delete':        
        post_id = request.POST.get('post_id')
        anomaly_id = request.POST.get('anomaly_id')
        post = Post.objects.filter(id=post_id).delete()
        anomaly = Anomaly.objects.filter(id=anomaly_id).delete()
    reports = AnomalySignal.objects.all()    
    context = {'menu': menu, 'reports': reports}
    return render(request, 'reports.html', context)

@staff_member_required
def dashboard_reports_edit(request):
    menu_active('Signalements')
    context = {'menu': menu, }
    return render(request, 'reports.html', context)

dashboard/templates/includes/anomalie_form.html
<form method="post" action="{% url 'dashboard:dashboard_anomalie_edit' post.id %}">
	{% csrf_token %}
	<input id="action" type="text" name="action" value="edit" hidden>		
	<input type="text" name="post_id" id="post_id" value="{{post.id}}" hidden>
	{% for field in form %}
	    <div class="form-group">	    	
		    {{field.label}}
		    {{field}}
	    </div>
	{% endfor %}
	<button class="btn btn-warning" type="submit">Modifier</button>
</form>

dashboard/templates/includes/base_script.html
{% load staticfiles %}
  <!--   Core JS Files   -->
  <script src="{% static 'js/core/jquery.min.js' %}"></script>
  <script src="{% static 'js/core/popper.min.js' %}"></script>
  <script src="{% static 'js/core/bootstrap-material-design.min.js' %}"></script>
  <script src="{% static 'js/plugins/perfect-scrollbar.jquery.min.js' %}"></script>
  <!-- Plugin for the momentJs  -->
  <script src="{% static 'js/plugins/moment.min.js' %}"></script>
  <!--  Plugin for Sweet Alert -->
  <script src="{% static 'js/plugins/sweetalert2.js' %}"></script>
  <!-- Forms Validations Plugin -->
  <script src="{% static 'js/plugins/jquery.validate.min.js' %}"></script>
  <!-- Plugin for the Wizard, full documentation here: https://github.com/VinceG/twitter-bootstrap-wizard -->
  <script src="{% static 'js/plugins/jquery.bootstrap-wizard.js' %}"></script>
  <!--  Plugin for Select, full documentation here: http://silviomoreto.github.io/bootstrap-select -->
  <script src="{% static 'js/plugins/bootstrap-selectpicker.js' %}"></script>
  <!--  Plugin for the DateTimePicker, full documentation here: https://eonasdan.github.io/bootstrap-datetimepicker/ -->
  <script src="{% static 'js/plugins/bootstrap-datetimepicker.min.js' %}"></script>
  <!--  DataTables.net Plugin, full documentation here: https://datatables.net/  -->
  <script src="{% static 'js/plugins/jquery.dataTables.min.js' %}"></script>
  <!--  Plugin for Tags, full documentation here: https://github.com/bootstrap-tagsinput/bootstrap-tagsinputs  -->
  <script src="{% static 'js/plugins/bootstrap-tagsinput.js' %}"></script>
  <!-- Plugin for Fileupload, full documentation here: http://www.jasny.net/bootstrap/javascript/#fileinput -->
  <script src="{% static 'js/plugins/jasny-bootstrap.min.js' %}"></script>
  <!--  Full Calendar Plugin, full documentation here: https://github.com/fullcalendar/fullcalendar    -->
  <script src="{% static 'js/plugins/fullcalendar.min.js' %}"></script>
  <!-- Vector Map plugin, full documentation here: http://jvectormap.com/documentation/ -->
  <script src="{% static 'js/plugins/jquery-jvectormap.js' %}"></script>
  <!--  Plugin for the Sliders, full documentation here: http://refreshless.com/nouislider/ -->
  <script src="{% static 'js/plugins/nouislider.min.js' %}"></script>
  <!-- Include a polyfill for ES6 Promises (optional) for IE11, UC Browser and Android browser support SweetAlert -->
  <script src="//cdnjs.cloudflare.com/ajax/libs/core-js/2.4.1/core.js"></script>
  <!-- Library for adding dinamically elements -->
  <script src="{% static 'js/plugins/arrive.min.js' %}"></script>
  <!-- Chartist JS -->
  <script src="{% static 'js/plugins/chartist.min.js' %}"></script>
  <!--  Notifications Plugin    -->
  <script src="{% static 'js/plugins/bootstrap-notify.js' %}"></script>
  <!-- Control Center for Material Dashboard: parallax effects, scripts for the example pages etc -->
  <script src="{% static 'js/material-dashboard.js' %}" type="text/javascript"></script>
  <script>
    $(document).ready(function() {

      var resizeEvent = new Event('resize');
      window.dispatchEvent(resizeEvent);

      $().ready(function() {
        $sidebar = $('.sidebar');

        $sidebar_img_container = $sidebar.find('.sidebar-background');

        $full_page = $('.full-page');

        $sidebar_responsive = $('body > .navbar-collapse');

        window_width = $(window).width();

        fixed_plugin_open = $('.sidebar .sidebar-wrapper .nav li.active a p').html();

        if (window_width > 767 && fixed_plugin_open == 'Dashboard') {
          if ($('.fixed-plugin .dropdown').hasClass('show-dropdown')) {
            $('.fixed-plugin .dropdown').addClass('open');
          }

        }

        $('.fixed-plugin a').click(function(event) {
          // Alex if we click on switch, stop propagation of the event, so the dropdown will not be hide, otherwise we set the  section active
          if ($(this).hasClass('switch-trigger')) {
            if (event.stopPropagation) {
              event.stopPropagation();
            } else if (window.event) {
              window.event.cancelBubble = true;
            }
          }
        });

        $('.fixed-plugin .active-color span').click(function() {
          $full_page_background = $('.full-page-background');

          $(this).siblings().removeClass('active');
          $(this).addClass('active');

          var new_color = $(this).data('color');

          if ($sidebar.length != 0) {
            $sidebar.attr('data-color', new_color);
          }

          if ($full_page.length != 0) {
            $full_page.attr('filter-color', new_color);
          }

          if ($sidebar_responsive.length != 0) {
            $sidebar_responsive.attr('data-color', new_color);
          }
        });

        $('.fixed-plugin .background-color .badge').click(function() {
          $(this).siblings().removeClass('active');
          $(this).addClass('active');

          var new_color = $(this).data('background-color');

          if ($sidebar.length != 0) {
            $sidebar.attr('data-background-color', new_color);
          }
        });

        $('.fixed-plugin .img-holder').click(function() {
          $full_page_background = $('.full-page-background');

          $(this).parent('li').siblings().removeClass('active');
          $(this).parent('li').addClass('active');


          var new_image = $(this).find("img").attr('src');

          if ($sidebar_img_container.length != 0 && $('.switch-sidebar-image input:checked').length != 0) {
            $sidebar_img_container.fadeOut('fast', function() {
              $sidebar_img_container.css('background-image', 'url("' + new_image + '")');
              $sidebar_img_container.fadeIn('fast');
            });
          }

          if ($full_page_background.length != 0 && $('.switch-sidebar-image input:checked').length != 0) {
            var new_image_full_page = $('.fixed-plugin li.active .img-holder').find('img').data('src');

            $full_page_background.fadeOut('fast', function() {
              $full_page_background.css('background-image', 'url("' + new_image_full_page + '")');
              $full_page_background.fadeIn('fast');
            });
          }

          if ($('.switch-sidebar-image input:checked').length == 0) {
            var new_image = $('.fixed-plugin li.active .img-holder').find("img").attr('src');
            var new_image_full_page = $('.fixed-plugin li.active .img-holder').find('img').data('src');

            $sidebar_img_container.css('background-image', 'url("' + new_image + '")');
            $full_page_background.css('background-image', 'url("' + new_image_full_page + '")');
          }

          if ($sidebar_responsive.length != 0) {
            $sidebar_responsive.css('background-image', 'url("' + new_image + '")');
          }
        });

        $('.switch-sidebar-image input').change(function() {
          $full_page_background = $('.full-page-background');

          $input = $(this);

          if ($input.is(':checked')) {
            if ($sidebar_img_container.length != 0) {
              $sidebar_img_container.fadeIn('fast');
              $sidebar.attr('data-image', '#');
            }

            if ($full_page_background.length != 0) {
              $full_page_background.fadeIn('fast');
              $full_page.attr('data-image', '#');
            }

            background_image = true;
          } else {
            if ($sidebar_img_container.length != 0) {
              $sidebar.removeAttr('data-image');
              $sidebar_img_container.fadeOut('fast');
            }

            if ($full_page_background.length != 0) {
              $full_page.removeAttr('data-image', '#');
              $full_page_background.fadeOut('fast');
            }

            background_image = false;
          }
        });

        $('.switch-sidebar-mini input').change(function() {
          $body = $('body');

          $input = $(this);

          if (md.misc.sidebar_mini_active == true) {
            $('body').removeClass('sidebar-mini');
            md.misc.sidebar_mini_active = false;

            $('.sidebar .sidebar-wrapper, .main-panel').perfectScrollbar();

          } else {

            $('.sidebar .sidebar-wrapper, .main-panel').perfectScrollbar('destroy');

            setTimeout(function() {
              $('body').addClass('sidebar-mini');

              md.misc.sidebar_mini_active = true;
            }, 300);
          }

          // we simulate the window Resize so the charts will get updated in realtime.
          var simulateWindowResize = setInterval(function() {
            window.dispatchEvent(new Event('resize'));
          }, 180);

          // we stop the simulation of Window Resize after the animations are completed
          setTimeout(function() {
            // clearInterval(simulateWindowResize);
            var resizeEvent = new Event('resize');
            window.dispatchEvent(resizeEvent);
            alert("Done");
          }, 10000);

          //Refresh graph
          $( "#dailySalesChart" ).load(window.location.href + "#dailySalesChart" );

        });
      });
    });
  </script>

dashboard/templates/includes/table_anomalies.html
          <div class="row">
            <div class="col-md-12">
              <div class="card">
                <div class="card-header">
                  <h4 class="card-title ">Anomalies</h4>
                  <p class="card-category">Consult, edit or delete.</p>
                </div>
                <div class="card-body">
                  <div class="table-responsive">
                    <table class="table">
                      <thead class=" text-primary">
                        <th>ID</th>
                        <th>Category</th>
                        <th>Description</th>
                        <th>Image</th>
                        <th>User</th>
                        <th>Score</th>
                        <th>Action</th>
                      </thead>
                      <tbody>
                        {% for a in anomalies %}
                        <tr>
                          <td class="text-primary">{{a.post.id}}</td>
                          <td>{{a.post.title}}</td>
                          <td>{{a.post.description}}</td>
                          <td><a href ="{{a.post.image}}" target="blank"><img src="{{a.post.image}}" style="height: 10vw; width: auto;"></a></td>
                          <td class="text-primary">{{a.post.post_owner.username}}</td>
                          <td>{{a.post.count_reactions}}</td>
                          <td>
                            <a href="{% url 'dashboard:dashboard_anomalie_edit' a.post.id %}" class="btn btn-warning btn-sm text-white">Edit</a>
                            <a href="{% url 'dashboard:dashboard_anomalie_archive' a.post.id %}" class="btn btn-success btn-sm text-white">Archive</a>
                            <form method="POST" action="/dashboard/anomalies">
                               {% csrf_token %}
                              <input id="action" type="text" name="action" value="delete" hidden>
                              <input id="post_id" type="text" name="post_id" value="{{a.post.id}}" hidden>
                              <button class="btn btn-danger btn-sm text-white" type="submit">Delete</button>
                            </form>
                          </td>
                        </tr>
                        {% endfor %}
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>

dashboard/templates/includes/table_comments.html
          <div class="row">
            <div class="col-md-12">
              <div class="card">
                <div class="card-header">
                  <h4 class="card-title ">Commentaires</h4>
                  <p class="card-category">Consult, edit or delete.</p>
                </div>
                <div class="card-body">
                  <div class="table-responsive">
                    <table class="table">
                      <thead class=" text-primary">
                        <th>ID du commentaire</th>
                        <th>Commentaire</th>
                        <th>Auteur</th>
                        <th>ID du Post</th>
                        <th>Titre du Post</th>
                        <th>Action</th>
                      </thead>
                      <tbody>
                        {% for c in comments %}
                        <tr>
                          <td class="text-primary">{{c.id}}</td>
                          <td>{{c.description}}</td>
                          <td>@{{c.comment_owner.username}} ({{c.comment_owner.first_name}} {{c.comment_owner.last_name}})</td>
                          <td>{{c.post.id}}</td>
                          <td>{{c.post.title}}</td>
                          <td>
                            <a href="{% url 'dashboard:dashboard_anomalie_edit' c.id %}" class="btn btn-warning text-white">Edit</a>
                            <form method="post" action="/dashboard/users">
                               {% csrf_token %}
                              <input id="action" type="text" name="action" value="delete" hidden>
                              <input id="post_id" type="text" name="user_id" value="{{u.id}}" hidden>
                              <button class="btn btn-danger text-white" type="submit">Delete</button>
                            </form>
                          </td>
                        </tr>
                        {% endfor %}
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>

dashboard/templates/includes/table_events.html
          <div class="row">
            <div class="col-md-12">
              <div class="card">
                <div class="card-header">
                  <h4 class="card-title ">Events</h4>
                  <p class="card-category">Consult, edit or delete.</p>
                </div>
                <div class="card-body">
                  <div class="table-responsive">
                    <table class="table">
                      <thead class=" text-primary">
                        <th>ID</th>
                        <th>Category</th>
                        <th>Description</th>
                        <th>Image</th>
                        <th>Date</th>
                        <th>User</th>
                        <th>Status</th>
                        <th>Apprové par</th>
                        <th>Date d'approbation</th>
                        <th>Score</th>
                        <th>Action</th>
                      </thead>
                      <tbody>
                        {% for e in events %}
                        <tr>
                          <td class="text-primary">{{e.post.id}}</td>
                          <td>{{e.post.title}}</td>
                          <td class="desc" title="{{e.post.description}}">{{e.post.description}}</td>
                          <td><a href ="{{e.post.image}}" target="blank"><img src="{{e.post.image}}" style="height: 10vw; width: auto; max-width: 10vw;"></a></td>
                          <td>{{e.starts_at}}</td>
                          <td class="text-primary">{{e.post.post_owner.username}}</td>
                          <td>{{e.status}}</td>
                          <td>{{e.approved_by}}</td>
                          <td>{{e.approved_at}}</td>
                          <td>{{e.post.count_reactions}}</td>
                          <td>
                            <!-- <a href="{% url 'dashboard:dashboard_anomalie_edit' e.post.id %}" class="btn btn-warning text-white">Edit</a> -->
                            {% if e.status != 'approved' %}
                            <a href="{% url 'dashboard:dashboard_event_approve' e.id %}" class="btn btn-success text-white">Approve</a>
                            {% endif %}
                            <form method="POST" action="/dashboard/anomalies">
                               {% csrf_token %}
                              <input id="action" type="text" name="action" value="delete" hidden>
                              <input id="post_id" type="text" name="post_id" value="{{e.post.id}}" hidden>
                              <button class="btn btn-danger text-white" type="submit">Delete</button>
                            </form>
                          </td>
                        </tr>
                        {% endfor %}
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>