Event/urls.py
from django.urls import path, include
from Event.Api.api import EventAPIView, EventRudView, EventParticipationAPIView, EventParticipationRudView


api_urlpatterns = [
    path('', EventAPIView.as_view(), name='event-listCreate'),
    path('<pk>', EventRudView.as_view(), name='event-rud'),
    path('participate/', EventParticipationAPIView.as_view(), name='eventParticipation-listCreate'),
    path('participate/<pk>', EventParticipationRudView.as_view(), name='eventParticipation-rud'),
]

urlpatterns = [
    path('', include(api_urlpatterns)),     # api url patterns
]

Post/urls.py
from django.urls import path, include
from Post.Api.api import PostAPIView, PostRudView, CommentAPIView, CommentRudView, ReactionAPIView, ReactionRudView, PictureAPIView, PictureRudView
from . import views

api_urlpatterns = [
    path('post/', PostAPIView.as_view(), name='post-listCreate'),
    path('post/<pk>', PostRudView.as_view(), name='post-rud'),
    path('post/<pk>/comment', views.post_comments, name='post_comments'),
    path('post/<pk>/picture', views.post_picture, name='post_picture'),


    path('comment/', CommentAPIView.as_view(), name='comment-listCreate'),
    path('comment/<pk>', CommentRudView.as_view(), name='comment-rud'),

    path('reaction/', ReactionAPIView.as_view(), name='reaction-listCreate'),
    path('reaction/<pk>', ReactionRudView.as_view(), name='reaction-rud'),
    path('reaction/user/<pk>', views.user_reactions, name='user_reactions'),

    path('picture/', PictureAPIView.as_view(), name='pictureCreate'),
    path('picture/<pk>', PictureRudView.as_view(), name='picture-rud'),

]

urlpatterns = [
    path('', include(api_urlpatterns)),     # api url patterns
]

SbaClean/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from rest_framework.authtoken.views import obtain_auth_token
from django.conf import settings
from django.conf.urls.static import static
from rest_framework_swagger.views import get_swagger_view
from django.contrib.auth import views as auth_views
from webapp.views import UploadView
from webapp import views
from django.conf.urls import handler404, handler500

schema_view = get_swagger_view(title='SbaClean API')
api_urlpatterns = [
    path('', schema_view),
    path('accounts/', include(('Accounts.urls', 'Accounts'), namespace='api-accounts')),
    path('address/', include(('Address.urls', 'Address'), namespace='api-address')),
    path('posts/', include(('Post.urls', 'Post'), namespace='api-posts')),
    path('anomalys/', include(('Anomaly.urls', 'Anomaly'), namespace='api-anomaly')),
    path('events/', include(('Event.urls', 'Event'), namespace='api-event')),
    path('mobile/', include('mobile.urls')),
    path('notification/', include('notification.urls')),

]

urlpatterns = [
                  path('', views.index),
                  path('login/', views.login, name='login'),
                  path('accounts/login/', views.login, name='login'),
                  path('register/', views.register, name='register'),
                  path('feed/', views.feed, name='feed'),
                  path('event/', views.event, name='event'),
                  path('profile/', views.profile, name='profile'),
                  path('post_details/', views.feed, name='post_details'),
                  path('social-auth/', views.social_auth, name='social_auth'),
                  path('', include('social_django.urls', namespace='social')),
                  path("logout/", views.logout, name="logout"),
                  path('', include('dashboard.urls', namespace='dashboard')),
                  path('api/upload-image', UploadView.as_view()),


    path('admin/', admin.site.urls),
    path('api-token-auth/', obtain_auth_token, name='api_token_auth'),
    path('api/v1/', include(api_urlpatterns)),
    url(r'^rest-auth/', include('rest_auth.urls')),
    url(r'^like/$',views.like_post,name="like_post"),
    url(r'^dislike/$',views.dislike_post,name="dislike_post"),
    url(r'^signaled/$',views.signaled,name="signaled"),
    url(r'^post_delete/$',views.post_delete,name="post_delete"),
    url(r'^post_edit/$',views.post_edit,name="post_edit"),
    url(r'^Myposts/$',views.Myposts,name="Myposts"),
    url(r'^Myreactions/$',views.Myreactions,name="Myreactions"),
    url(r'^comment_delete/$',views.comment_delete,name="comment_delete"),
    url(r'^create_comment/$',views.create_comment,name="create_comment"),
    url(r'^Participate/$',views.Participate,name="Participate")


              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



handler404 = views.error_404
handler500 = views.error_500

Post/models.py
from django.db import models
from Accounts.models import MyUser
from Address.models import State, City
import os


class Post(models.Model):
    title = models.TextField(max_length=255, default='Title')
    post_owner = models.ForeignKey(MyUser, on_delete=models.CASCADE)
    description = models.TextField(max_length=255)
    city = models.ForeignKey(City, related_name='location', on_delete=models.CASCADE)
    longitude = models.CharField(max_length=255)
    image = models.CharField(max_length=255,
                             default='https://www.eltis.org/sites/default/files/styles/web_quality/public/default_images/photo_default_2.png')
    latitude = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)

    def count_reactions(self):
        likes_count = Reaction.objects.filter(post=self.id, is_like=True).count()
        dislikes_count = Reaction.objects.filter(post=self.id, is_like=False).count()
        return likes_count - dislikes_count

    def count_comments(self):
        Comments_count = Comment.objects.filter(post = self.id).count()
        return Comments_count
    
    def get_user(self):
        user = MyUser.objects.get(id = self.post_owner.id)
        payload = {
            "id" : user.pk,
            "username" : user.username,
            "email" : user.email,
            
        }
        return payload

    def owner(self):
        return self.post_owner


class Comment(models.Model):
    comment_owner = models.ForeignKey(MyUser, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
    description = models.TextField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)

    def owner(self):
        return self.comment_owner
    
    def get_user(self):
        user = MyUser.objects.get(id = self.comment_owner.id)
        payload = {
            "id" : user.pk,
            "username" : user.username
        }

        return payload


class Reaction(models.Model):
    reaction_owner = models.ForeignKey(MyUser, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, related_name='reactions', on_delete=models.CASCADE)
    is_like = models.BooleanField(null=False)

    def owner(self):
        return self.reaction_owner


def get_picture_path(instance, filename):
    return os.path.join('Posts', str(instance.id), filename)


class Picture(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    photo_path = models.CharField(max_length=255,
                                  default='https://summer.pes.edu/wp-content/uploads/2019/02/default-2.jpg')

webapp/views.py
from django.contrib.auth import authenticate
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.http import *
from django.shortcuts import render, get_object_or_404, redirect, render_to_response
from django.template import RequestContext
from django.urls import reverse
from django.utils.translation import gettext as _
from django.db import transaction
from rest_framework.parsers import MultiPartParser, JSONParser
from rest_framework.views import APIView
import cloudinary.uploader
from .models import *
from Post.models import *
from Event.models import *
from Anomaly.models import *
from Accounts.models import *
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
from .form import *
import base64
import requests
from social_django.utils import psa, load_strategy
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db.models.aggregates import Count
from django.db.models import Q
from django.db.models.query import QuerySet
from datetime import datetime

UserModel = get_user_model()

def upload_image(image):
    url = 'https://image-cloudinary.herokuapp.com/photos'
    files = {'image': image}
    response = requests.post(url, files=files)
    return response.json()['url']
def notifications(request):
    # Getting actual number of Users, Anomalies, Events and archives
    posts=Post.objects.filter(post_owner=request.user)
    events=Event.objects.filter(post__in=posts)
    comments_count = Comment.objects.filter(post__in=posts).count()
    reactions_count = Reaction.objects.filter(post__in=posts).count()
    participations_count = EventParticipation.objects.filter(event__in=events).count()
    


    # Getting the session stored numbers
    if not request.session.get('comments_count'):
        request.session['comments_count'] = comments_count
    my_comments_count = request.session['comments_count']
    request.session['comments_count'] = comments_count

    if not request.session.get('reactions_count'):
        request.session['reactions_count'] = reactions_count
    my_reactions_count = request.session['reactions_count']
    request.session['reactions_count'] = reactions_count

    if not request.session.get('participations_count'):
        request.session['participations_count'] = participations_count
    my_participations_count = request.session['participations_count']
    request.session['participations_count'] = participations_count


    notifications = {
        "comments_count": comments_count - my_comments_count,
        "reactions_count": reactions_count - my_reactions_count,
        "participations_count": participations_count - my_participations_count,
    }
    return notifications

def index(request):
    if request.user.is_authenticated :
        return redirect('/feed')
    else:
        context = {}
        return render(request, 'index.html', context)


@login_required
def account(request):
    context = {}
    return render(request, 'account.html', context)

class UploadView(APIView):
    parser_classes = (
        MultiPartParser,
        JSONParser,
    )

@login_required
def feed(request):
        user = request.user
        username = request.user.username
        postCity=Post.objects.filter(city=user.city)
        posts=Anomaly.objects.filter(archived=False)
        anomalySignal=AnomalySignal.objects.filter(user= request.user)
        participant=EventParticipation.objects.filter(user=user)
        notif = notifications(request)
        date_part=[]
        for part in participant:
                if part.event.starts_at.date() == datetime.today().date():
                        date_part.append({'event':part.event.post.title,'hour':part.event.starts_at.hour,'minute':part.event.starts_at.minute})


        user_pic_post=[]
        for post in postCity:
                user_pic_post.append({'post':post,'post_owner':post.post_owner,'user_pic':base64.urlsafe_b64encode(post.post_owner.username.encode())})
        comments=Comment.objects.all()
        user_pic_comment=[]
        for comment in comments:
                user_pic_comment.append({'comment':comment,'comment_owner':comment.comment_owner,'user_pic':base64.urlsafe_b64encode(comment.comment_owner.username.encode())})
        reactions= Reaction.objects.filter(reaction_owner=request.user)
        user_pic=base64.urlsafe_b64encode(username.encode())
        userId= request.user.id
        qs = MyUser.objects.all()
        query_limit = 5
        like_creat_nember=[]
        for reaction in reactions:
                like_creat_nember.append(reaction.post)

        if query_limit is not None:
                # get all users of the same city
                users = MyUser.objects.filter(city=user.city)
                user_pic_user=[]
                for user in users:
                        user_pic_user.append({'user':user,'user_pic':base64.urlsafe_b64encode(user.username.encode())})
                posts2=posts
                

                # Then doing the calculations
                users = users.annotate(rank_point=(Count('post__reactions', filter=Q(post__reactions__is_like=True)) - (
                        Count('post__reactions', filter=Q(post__reactions__is_like=False))))).filter(rank_point__gt=0)
                posts2 = posts2.annotate(rank_point=(Count('post__reactions', filter=Q(post__reactions__is_like=True)) )).filter(rank_point__gt=0)
                # And finaly, order the results
                users = users.order_by('-rank_point')[:query_limit]
                posts2=posts2.order_by('-rank_point')[:query_limit]
        if request.method == 'POST':
                form=UserComment(request.POST or None)
                form2=UserPost(request.POST or None)
                if form.is_valid():
                        if request.POST.get('post_id'):
                                post_id=int(request.POST.get('post_id'))
                                post=get_object_or_404(Post,id=post_id)
                                description=request.POST.get('description')
                                comment=Comment.objects.create(post=post, comment_owner=request.user,description=description)
                                comment.save()
                if form2.is_valid():
                        if request.FILES: 
                                image= request.FILES['image'].read()
                                # upload_data = cloudinary.uploader.upload(image)
                                # image=upload_data['url']
                                image=upload_image(image)
                                title = request.POST.get('title')
                                city = request.POST.get('city')
                                longitude = request.POST.get('longitude')
                                latitude = request.POST.get('latitude')
                                description=request.POST.get('description')
                                post=Post.objects.create(title=title, post_owner=request.user,description=description,city=get_object_or_404(City,id=city),longitude=longitude,latitude=latitude,image=image)
                                post.save()
                        else:
                                title = request.POST.get('title')
                                city = request.POST.get('city')
                                longitude = request.POST.get('longitude')
                                latitude = request.POST.get('latitude')
                                description=request.POST.get('description')
                                post=Post.objects.create(title=title, post_owner=request.user,description=description,city=get_object_or_404(City,id=city),longitude=longitude,latitude=latitude)
                                post.save()
                        
                        anomaly=Anomaly.objects.create(post=post,signaled=False)
                        anomaly.save()
        else:
                form=UserComment()
                form2=UserPost()            
        context = {'username':username,'user_pic':user_pic,'users':users,'posts':posts,'userId':userId,'comments':comments,'form':form,'form2':form2,'reactions':reactions,
        'like_creat_nember':like_creat_nember,'posts2':posts2,'user_pic_post':user_pic_post,'user_pic_comment':user_pic_comment,'user_pic_user':user_pic_user,
        'anomalySignal':anomalySignal,'date_part':date_part,'notification':notif}         
        return render(request, 'feed.html', context)

def create_comment(request):
        if request.method == 'POST':
                post_id=int(request.POST['post_id'])
                post=get_object_or_404(Post,id=post_id)
                description=request.POST['description']
                Comment.objects.create(post=post, comment_owner=request.user,description=description)
                
        return HttpResponse('')

@login_required
def event(request):
        user = request.user
        username = request.user.username
        postCity=Post.objects.filter(city=user.city)
        Myposts=Post.objects.filter(post_owner=user)
        events2=Event.objects.filter(post__in=Myposts)
        events=Event.objects.filter(post__in= postCity,starts_at__gte = datetime.today()).exclude(approved_at=None)
        participants=EventParticipation.objects.filter(event__in=events2)
        nb_participante=[]
        for event in events:
                nb_participante.append({'event':event,'nb_part':EventParticipation.objects.filter(event=event).count(),'is_part':EventParticipation.objects.filter(event=event,user=request.user)})
        user_pic_post=[]
        for post in postCity:
                user_pic_post.append({'post':post,'post_owner':post.post_owner,'user_pic':base64.urlsafe_b64encode(post.post_owner.username.encode())})

webapp/templates/404_page.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>SBA CLEAN</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="" />
<meta name="keywords" content="" />
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->
<style>
body {
    background: #dedede;
}
.page-wrap {
    min-height: 100vh;
}
</style>
</head>
<body>
<div class="page-wrap d-flex flex-row align-items-center">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 text-center">
                <span class="display-1 d-block">404</span>
                <div class="mb-4 lead">The page you are looking for was not found.</div>
                <a href="{% url 'feed' %}" class="btn btn-link">Back to Home</a>
            </div>
        </div>
    </div>
</div>
</body>

webapp/templates/500_page.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>SBA CLEAN</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="" />
<meta name="keywords" content="" />
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->
</head>
<body>
<div class="page-wrap d-flex flex-row align-items-center">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 text-center">
                <span class="display-1 d-block">500</span>
                <div class="mb-4 lead">The page you are looking for was not found.</div>
                <a href="{% url 'feed' %}" class="btn btn-link">Back to Home</a>
            </div>
        </div>
    </div>
</div>
</body>

webapp/templates/Myposts.html
{% extends 'layouts/base_Myposts.html' %}
{% load staticfiles %}
{% block title %}Myposts{% endblock %}
{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'css/feed.css' %}">
<link href="https://fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,500,500i,700,700i" rel="stylesheet">

{% endblock %}


{% block content_header %}
{% include 'includes/header_feed.html' %}
{% endblock %}


{% block content_user_data %}
{% include 'includes/user_data.html' %}
{% endblock %}


{% block content_tags_sec %}
{% include 'includes/tags-sec.html' %}
{% endblock %}


{% block content_post_comment %}
{% include 'includes/Mypost_comment.html' %}
{% endblock %}


{% block content_widget_about %}
{% include 'includes/widget_about.html' %}
{% endblock %}


{% block content_widget_week %}
{% include 'includes/widget_week.html' %}
{% endblock %}


{% block content_suggestions%}
{% include 'includes/suggestions.html' %}
{% endblock %}

{% block scripte %}
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDCjArZEIzRmGeqtIQn0icqxuQW8G7Me4I&amp;libraries=places"></script>
         
<script>
  google.maps.event.addDomListener(window, 'load', initialize);
    function initialize() {
      var input = document.getElementById('autocomplete_search');
      var autocomplete = new google.maps.places.Autocomplete(input);
      autocomplete.addListener('place_changed', function () {
      var place = autocomplete.getPlace();
      // place variable will have all the information you are looking for.
      $('#id_latitude').val(place.geometry['location'].lat());
      $('#id_longitude').val(place.geometry['location'].lng());
    });
  }
  </script>
  <script>
  $(document)
    .one('focus.autoExpand', 'textarea.autoExpand', function(){
        var savedValue = this.value;
        this.value = '';
        this.baseScrollHeight = this.scrollHeight;
        this.value = savedValue;
    })
    .on('input.autoExpand', 'textarea.autoExpand', function(){
        var minRows = this.getAttribute('data-min-rows')|0, rows;
        this.rows = minRows;
        rows = Math.ceil((this.scrollHeight - this.baseScrollHeight) / 16);
        this.rows = minRows + rows;
    });
</script>
<script>
// Applied globally on all textareas with the "autoExpand" class
$(document)
    .one('focus.autoExpand', 'textarea.autoExpand', function(){
        var savedValue = this.value;
        this.value = '';
        this.baseScrollHeight = this.scrollHeight;
        this.value = savedValue;
    })
    .on('input.autoExpand', 'textarea.autoExpand', function(){
        var minRows = this.getAttribute('data-min-rows')|0, rows;
        this.rows = minRows;
        rows = Math.ceil((this.scrollHeight - this.baseScrollHeight) / 16);
        this.rows = minRows + rows;
    });
</script>
<script>
    document.getElementById('posts').classList.add("active");
</script>
{% endblock %}

webapp/templates/Myreactions.html
{% extends 'layouts/base_Myreactions.html' %}
{% load staticfiles %}
{% block title %}Myrections{% endblock %}
{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'css/feed.css' %}">
<link href="https://fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,500,500i,700,700i" rel="stylesheet">

{% endblock %}


{% block content_header %}
{% include 'includes/header_feed.html' %}
{% endblock %}


{% block content_user_data %}
{% include 'includes/user_data.html' %}
{% endblock %}


{% block content_tags_sec %}
{% include 'includes/tags-sec.html' %}
{% endblock %}


{% block content_post_comment %}
{% include 'includes/Myreaction_comment.html' %}
{% endblock %}


{% block content_widget_about %}
{% include 'includes/widget_about.html' %}
{% endblock %}


{% block content_widget_week %}
{% include 'includes/widget_week.html' %}
{% endblock %}


{% block content_suggestions%}
{% include 'includes/suggestions.html' %}
{% endblock %}

{% block scripte %}
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDCjArZEIzRmGeqtIQn0icqxuQW8G7Me4I&amp;libraries=places"></script>
         
<script>
  google.maps.event.addDomListener(window, 'load', initialize);
    function initialize() {
      var input = document.getElementById('autocomplete_search');
      var autocomplete = new google.maps.places.Autocomplete(input);
      autocomplete.addListener('place_changed', function () {
      var place = autocomplete.getPlace();
      // place variable will have all the information you are looking for.
      $('#id_latitude').val(place.geometry['location'].lat());
      $('#id_longitude').val(place.geometry['location'].lng());
    });
  }
  </script>
  <script>
  $(document)
    .one('focus.autoExpand', 'textarea.autoExpand', function(){
        var savedValue = this.value;
        this.value = '';
        this.baseScrollHeight = this.scrollHeight;
        this.value = savedValue;
    })
    .on('input.autoExpand', 'textarea.autoExpand', function(){
        var minRows = this.getAttribute('data-min-rows')|0, rows;
        this.rows = minRows;
        rows = Math.ceil((this.scrollHeight - this.baseScrollHeight) / 16);
        this.rows = minRows + rows;
    });
</script>
<script>
// Applied globally on all textareas with the "autoExpand" class
$(document)
    .one('focus.autoExpand', 'textarea.autoExpand', function(){
        var savedValue = this.value;
        this.value = '';
        this.baseScrollHeight = this.scrollHeight;
        this.value = savedValue;
    })
    .on('input.autoExpand', 'textarea.autoExpand', function(){
        var minRows = this.getAttribute('data-min-rows')|0, rows;
        this.rows = minRows;
        rows = Math.ceil((this.scrollHeight - this.baseScrollHeight) / 16);
        this.rows = minRows + rows;
    });
</script>
<script>
    document.getElementById('reactions').classList.add("active");
</script>
{% endblock %}

webapp/templates/event.html
{% extends 'layouts/base_feed.html' %}
{% load staticfiles %}
{% block title %}event{% endblock %}
{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'css/feed.css' %}">
<link href="https://fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,500,500i,700,700i" rel="stylesheet">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/leaflet/1/leaflet.css" />
<script src="https://cdn.jsdelivr.net/leaflet/1/leaflet.js"></script>
{% endblock %}


{% block content_header %}
{% include 'includes/header_feed.html' %}
{% endblock %}


{% block content_user_data %}
{% include 'includes/user_data.html' %}
{% endblock %}


{% block content_tags_sec %}
{% include 'includes/tags-sec.html' %}
{% endblock %}


{% block content_post_comment %}
{% include 'includes/event_comment.html' %}
{% endblock %}


{% block content_widget_about %}
{% include 'includes/widget_about.html' %}
{% endblock %}


{% block content_widget_week %}
{% include 'includes/widget_week.html' %}
{% endblock %}


{% block content_suggestions%}
{% include 'includes/suggestions.html' %}
{% endblock %}

{% block scripte %}
<script src="https://cdn.jsdelivr.net/npm/places.js@1.16.4"></script>
<script>
(function() {
  var placesAutocomplete = places({
    appId: 'plRYOX92LH60',
    apiKey: 'bcbd136f8826254d843299d2767a0612',
    container: document.querySelector('#input-map')
  });

  var map = L.map('map-example-container', {
    scrollWheelZoom: false,
    zoomControl: false
  });

  var osmLayer = new L.TileLayer(
    'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
      minZoom: 1,
      maxZoom: 13,
      attribution: 'Map data © <a href="https://openstreetmap.org">OpenStreetMap</a> contributors'
    }
  );

  var markers = [];

  map.setView(new L.LatLng(0, 0), 1);
  map.addLayer(osmLayer);

  placesAutocomplete.on('suggestions', handleOnSuggestions);
  placesAutocomplete.on('cursorchanged', handleOnCursorchanged);
  placesAutocomplete.on('change', handleOnChange);
  placesAutocomplete.on('clear', handleOnClear);

  function handleOnSuggestions(e) {
    markers.forEach(removeMarker);
    markers = [];

    if (e.suggestions.length === 0) {
      map.setView(new L.LatLng(0, 0), 1);
      return;
    }

    e.suggestions.forEach(addMarker);
    findBestZoom();
  }

  function handleOnChange(e) {
    markers
      .forEach(function(marker, markerIndex) {
        if (markerIndex === e.suggestionIndex) {
          markers = [marker];
          marker.setOpacity(1);
          findBestZoom();
        } else {
          removeMarker(marker);
        }
      });
      $('#id_latitude').val(e.suggestion.latlng.lat);
    $('#id_longitude').val(e.suggestion.latlng.lng);
  }

  function handleOnClear() {
    map.setView(new L.LatLng(0, 0), 1);
    markers.forEach(removeMarker);
  }

  function handleOnCursorchanged(e) {
    markers
      .forEach(function(marker, markerIndex) {
        if (markerIndex === e.suggestionIndex) {
          marker.setOpacity(1);
          marker.setZIndexOffset(1000);
        } else {
          marker.setZIndexOffset(0);
          marker.setOpacity(0.5);
        }
      });
  }

  function addMarker(suggestion) {
    var marker = L.marker(suggestion.latlng, {opacity: .4});
    marker.addTo(map);
    markers.push(marker);
  }

  function removeMarker(marker) {
    map.removeLayer(marker);
  }

  function findBestZoom() {
    var featureGroup = L.featureGroup(markers);
    map.fitBounds(featureGroup.getBounds().pad(0.5), {animate: false});
  }
})();
</script>
  <script>
  $(document)
    .one('focus.autoExpand', 'textarea.autoExpand', function(){
        var savedValue = this.value;
        this.value = '';
        this.baseScrollHeight = this.scrollHeight;
        this.value = savedValue;
    })
    .on('input.autoExpand', 'textarea.autoExpand', function(){
        var minRows = this.getAttribute('data-min-rows')|0, rows;
        this.rows = minRows;
        rows = Math.ceil((this.scrollHeight - this.baseScrollHeight) / 16);
        this.rows = minRows + rows;
    });
</script>
<script>
// Applied globally on all textareas with the "autoExpand" class
$(document)
    .one('focus.autoExpand', 'textarea.autoExpand', function(){
        var savedValue = this.value;
        this.value = '';
        this.baseScrollHeight = this.scrollHeight;
        this.value = savedValue;
    })
    .on('input.autoExpand', 'textarea.autoExpand', function(){
        var minRows = this.getAttribute('data-min-rows')|0, rows;
        this.rows = minRows;
        rows = Math.ceil((this.scrollHeight - this.baseScrollHeight) / 16);
        this.rows = minRows + rows;
    });
</script>
<script>
    document.getElementById('evenement').classList.add("active");
   
</script>
{% endblock %}

webapp/templates/login.html
{% extends 'layouts/base_login.html' %}
{% load staticfiles %}
{% block title %}Login{% endblock %}
{% block content1 %}
	<div class="limiter">
		<div class="container-login100">
			{% include 'includes/form_login.html' %}
		</div>
	</div>
{% endblock %}

webapp/templates/register.html
{% extends 'layouts/base_login.html' %}
{% load staticfiles %}
{% block title %}Inscription{% endblock %}
{% block content1 %}
	<div class="limiter">
		<div class="container-login100">
			{% include 'includes/form_register.html' %}
		</div>
	</div>
{% endblock %}